"""fix ContentBlock type miss

Revision ID: 65fe2f2f775d
Revises: 6c8790b872ab
Create Date: 2026-03-25 16:35:02.389300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '65fe2f2f775d'
down_revision: Union[str, Sequence[str], None] = '6c8790b872ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    content_block_type = postgresql.ENUM(
        'text', 'image',
        name='content_block_type'
    )
    content_block_type.create(op.get_bind(), checkfirst=True)

    op.execute("""
        ALTER TABLE content_blocks
        ALTER COLUMN type TYPE content_block_type
        USING type::content_block_type
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        ALTER TABLE content_blocks
        ALTER COLUMN type TYPE VARCHAR(100)
        USING type::text
    """)

    content_block_type = postgresql.ENUM(
        'text', 'image',
        name='content_block_type'
    )
    content_block_type.drop(op.get_bind(), checkfirst=True)

