"""Add relationship between posts and their content blocks

Revision ID: fb2ab9cb17ea
Revises: 899d5b0f2545
Create Date: 2026-03-19 14:34:36.493024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb2ab9cb17ea'
down_revision: Union[str, Sequence[str], None] = '899d5b0f2545'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'content_blocks', 'posts', ['post_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'content_blocks', type_='foreignkey')
    # ### end Alembic commands ###
